message: Greetings from the PRODUCT-QUERY-SIDE microservice [using the PRODUCTION config].

eureka:
  client:
    serviceUrl:
      defaultZone: http://spaxon-discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: spaxon.events.fanout.exchange
        queue: spaxon.default.queue
        terminal: spaxon.axon.terminal
    rabbitmq:
        hostname: spaxon-rabbitmq
        username: test
        password: password
    data:
        rest:
            #base-path: api/v1
logging:
    level:
        root: WARN
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.spaxon: INFO
    file: ./logs/query-side-server.log
