message: Greetings from the PRODUCT-COMMAND-SIDE microservice [using the PRODUCTION config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://spaxon-discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: product.events.fanout.exchange
        queue: product.default.queue
        databaseName: products
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: spaxon-rabbitmq
        username: test
        password: password
    datasource:
        url: jdbc:mysql://spaxon-mysql:3306/spaxon
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        validation-query: SELECT 1
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    #data:
        #mongodb:
        #    host: spaxon-mongodb        
        #    uri: mongodb://spaxon-mongodb:27017/spaxon
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.spaxon: INFO
    file: ./logs/command-side-server.log
