message: Greetings from the PRODUCT-COMMAND-SIDE microservice [using the LOCALHOST config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: product.events.fanout.exchange
        queue: product.default.queue
        databaseName: products
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: localhost
        username: test
        password: password
    datasource:
        url: jdbc:mysql://localhost:3306/spaxon
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        validation-query: SELECT 1
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    devtools:
        remote: 
            secret: thisismysecret            
    #data:
        #mongodb:
            #host: localhost
            #uri: mongodb://localhost:27017/products
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.spaxon: INFO
    file: ./build/logs/command-side-server.log
